### ISSUE TITLE
Significant Increase in Scene Loading Time from Sionna 0.16.2 to 0.18

### ISSUE THREAD

**Issue by kjellwagn** [NVlabs/sionna#545] opened 2024-08-14 09:27 UTC
I have noticed a significant increase in the amount of time it takes to load a scene from a '.xml' file exported from Blender using Mitsuba after upgrading from Sionna version v0.16.2 to v0.18. The same '.xml' file that took 5 seconds to load now takes around 8 minutes in the new version. Also, the RAM usage exceeds 40 GB, which seems unusually high.

Tested versions:
Sionna 0.16.2 | tensorflow 2.15.0 | python 3.9.19
Sionna 0.18 | tensorflow 2.15.0 | python 3.9.19

Ubuntu 22.04.4

Is this increase in loading time and memory usage a known issue?
Could it be related to the new intelligent surfaces introduced in the latest version?

**Comment by SebastianCa** [comment] 2024-08-19 09:23
Hi @kjellwagn,
Does this behavior only occur when loading your custom scene, or do you also experience it with the built-in scenes?

Is your custom scene particularly large or does it contain a very detailed mesh?

**Comment by kjellwagn** [comment] 2024-08-19 13:11
Hey @SebastianCa ,

This also occurs with the built-in scenes, although the time increase is minimal. For example, the Munich scene takes an average of 5 seconds to load in v0.16.2 and 7.5 seconds in v0.18.
In fact, the custom scene being used is quite large and detailed, comprising about 5.5 million triangles.

**Comment by SebastianCa** [comment] 2024-08-20 09:24
That sounds like a fairly large scene. We’ll look into it and get back to you.

**Comment by merlinND** [comment] 2024-08-22 08:26
Hello @kjellwagn,

We have identified some performance regressions, and fixes will be included in the next release. Thanks for bringing it to our attention!

In terms of memory usage, I didn't measure a particular difference on the built-in Munich scene. Could you please share the scene where you've measured increased usage? Please include all meshes and the XML file.

**Comment by Xiaohei-Luo** [comment] 2024-08-26 05:38
'''
import threading
import multiprocessing
import mitsuba as mi
def load_thread(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
def load_process(filepath):
mi.set_variant("cuda_ad_rgb")
mi.load_file(filepath)
if name == "main":
paths = "test.xml"
#it works well.
process = multiprocessing.Process(target=load_process, args=(paths, ))
process.start()
process.join()
#it exited with exit code -1073741819 `(0xC0000005).
thread = threading.Thread(target=load_thread, args=(paths,))
thread.start()
thread.join()
'''

**Comment by merlinND** [comment] 2024-09-09 09:27
Thanks for sharing the scene.

I have done the following measurements with `nvtop` for memory usage & runtime:
![measurements](https://github.com/user-attachments/assets/4fbd3843-f1a5-45f1-b620-b011592f4b4e)

They all reach the same memory usage, mostly due to TensorFlow allocating a large memory arena from the start.
How did you measurement memory usage?

**Comment by jhoydis** [comment] 2024-10-02 10:38
Fixed in release 0.19.

**Closed by jhoydis** 2024-10-02 10:38 UTC
