### ISSUE TITLE
 Missing Path Detection in Sionna Simulations

### ISSUE THREAD

**Issue by Leeyyhh** [NVlabs/sionna#675] opened 2024-11-24 01:57 UTC
Hi, Everyone. Is it possible that Sionna fails to identify a line-of-sight (LOS) path in certain scenarios? During a simulation today, I observed that Sionna could not find a direct path from the transmitter to the receiver, despite the absence of obstacles, when I set the max_depth parameter to 2 using the code scene.compute_paths(max_depth=2). However, when I set max_depth to 1, it successfully found the LOS path. Could it be that some direct paths or strong reflected paths are not correctly identified during the simulation? Thanks a lot for your help!!

<img width="934" alt="4559676d1bae613b9bf3797810726f3" src="https://github.com/user-attachments/assets/b9de8e95-983b-49bd-88cf-790f7df04141">

**When I set max_depth to 1** 

<img width="875" alt="1732413528042" src="https://github.com/user-attachments/assets/2d7621ac-8fa4-4351-aefd-fa56d8ff1caa">

** I also try to increase the num_samples to  10**8 but it doesn't work 
<img width="894" alt="1732414945040" src="https://github.com/user-attachments/assets/7611fae0-3d13-441f-b286-14277b4616e1">

**Comment by faycalaa** [comment] 2024-11-25 08:59
That looks like a duplicate of #626, and will be fixed in the next release.

**Closed** 2024-11-25 15:18 UTC
