### ISSUE TITLE
Resource deadlock would occur when using load_scene

### ISSUE THREAD

**Issue by PhilSoy** [NVlabs/sionna#354] opened 2024-03-13 09:51 UTC
I get the following error message:  "​[xml.cpp:179] Error while loading "xxxxxxxxxxxxx.xml" (at line 8, col 3): resource deadlock would occur: resource deadlock would occur." the crash is caused by Sionna's load_scene
I tried many combinations of versions (for Blender and Mitsuba), and also tried with a file provided by a colleague working on Mac OS). But this did not solve the issue. 
Sionna works well with the Quickstart tutorials (not using .xml scenes imports)

It looks like the issue does not exist on Mac OS. Has anybody succeeded on Windows ?

**Comment by merlinND** [comment] 2024-03-13 13:39
Closing as duplicate of #293.

**Closed by merlinND** 2024-03-13 13:39 UTC
