### ISSUE TITLE
SceneObject.postion makes jupyter kernel crashes

### ISSUE THREAD

**Issue by SimoneDelPrete** [NVlabs/sionna#446] opened 2024-05-23 10:42 UTC
Hi, so I am learning how to use sionna. I loaded the scene floor_wall for simple tests. However, I try to print the position and orientation of the object wall:
```python
scene = load_scene(sionna.rt.scene.floor_wall)

wall: sionna.rt.SceneObject = scene.get("wall") 
print(f"Orientation = {wall.orientation.numpy()}")
print(f"Position = {wall.position.numpy()}")
``` 
With orientation is everything fine, but when I call wall.position the jupyter kernel crashes.

This is the log I get
```jupyter-notebook
13:40:37.001 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 2024-05-23 13:40:24.888169: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-23 13:40:24.931159: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-23 13:40:24.931190: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-23 13:40:24.931907: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-23 13:40:24.939283: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-23 13:40:25.882722: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-05-23 13:40:27.676522: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-23 13:40:27.724547: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

13:40:37.078 [info] Cell 1 completed in -1716460836.382s (start: 1716460836382, end: undefined)
``` 

EDIT: I forgot to say, I am on Windows 10 and I installed sionna in a WSL2 environment with Ubuntu

**Comment by SebastianCa** [comment] 2024-05-23 11:19
Hi @SimoneDelPrete,

I cannot reproduce the error on my machine (native Ubuntu and Sionna v0.v17). 
It seems like there is an issue with your TensorFlow/GPU driver installation. Did you check the [TensorFlow installation guide](https://www.tensorflow.org/install/pip#windows-wsl2)?

Could you please provide more details about the package versions (Python, TensorFlow and Sionna)?

**Comment by SimoneDelPrete** [comment] 2024-05-23 12:18
> Hi @SimoneDelPrete,
> 
> I cannot reproduce the error on my machine (native Ubuntu and Sionna v0.v17). It seems like there is an issue with your TensorFlow/GPU driver installation. Did you check the [TensorFlow installation guide](https://www.tensorflow.org/install/pip#windows-wsl2)?
> 
> Could you please provide more details about the package versions (Python, TensorFlow and Sionna)?

Yes. So, I am using my lenovo laptop with a NVIDIA GeForce MX350.

I have setup a virtual environment with venv using python 3.10.12

Sionna is 0.17.0

I have tensorflow 2.15.1. The output of python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))":
```shell
2024-05-23 15:12:28.951316: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-23 15:12:29.105879: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-23 15:12:29.106027: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-23 15:12:29.129396: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-23 15:12:29.198792: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-23 15:12:30.216890: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-05-23 15:12:31.637360: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-23 15:12:32.015944: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]
```

**Comment by SebastianCa** [comment] 2024-05-23 16:52
This seems to be an issue with your TensorFlow installation on WSL as the command above should return a list of available GPUs. Please follow the [TensorFlow installation guide](https://www.tensorflow.org/install/pip) and ensure that the GPU drivers are correctly installed.

I'll close this issue as it is not directly related to Sionna.

**Closed by SebastianCa** 2024-05-23 16:52 UTC
