### ISSUE TITLE
Got the channel coefficients as 0j

### ISSUE THREAD

**Issue by zhiha** [NVlabs/sionna#235] opened 2023-10-11 01:05 UTC
I have created an indoor scene, but when I computed the paths, I got many channel coefficients as 0j and some data propagation delays as 0. Is this normal?
```
--- Detailed results for path 1 ---
Channel coefficient: 0j
Propagation delay: 0.00000 us
Zenith angle of departure: 1.7286 rad
Azimuth angle of departure: -0.7854 rad
Zenith angle of arrival: 1.4130 rad
Azimuth angle of arrival: -0.7854 rad
```

My custom scene:
![image](https://github.com/NVlabs/sionna/assets/47016909/c3ad8199-7009-4e20-8865-26bf850b3fdc)

The obj of the scene:
```
Floor : itu_concrete
Wall1 : itu_concrete
Wall2 : itu_concrete
Wall3 : itu_concrete
Wall4 : itu_concrete
obj1 : itu_concrete
obj2 : itu_concrete
obj3 : itu_concrete
```

Use
```
paths = scene.compute_paths(max_depth=3,
                            num_samples=1e6)
```

**Comment by jhoydis** [comment] 2023-10-11 10:42
Hi,

This should not happen, but it is difficult to find the reason without having code to reproduce the issue.
The zero delay corresponds to the first paths that arrives. 
Having zero energy could only happen if the antenna or receiver pattern would equal zero in that particular direction or if the ``scattering_coefficient`` is set equal to one so that reflected paths have no energy.

**Comment by zhiha** [comment] 2023-10-11 10:46
here is my code:
```
%matplotlib inline
import numpy as np 
import tensorflow as tf
from sionna.rt import load_scene, Transmitter, Receiver, PlanarArray, Camera
import matplotlib.pyplot as plt
import os 
os.chdir("../")
scene = load_scene("./dataset/blender/room_init/room_init.xml")
for i, obj in enumerate(scene.objects.values()):
    print(f"{obj.name} : {obj.radio_material.name}")
scene.tx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="tr38901",
                             polarization="V")
scene.rx_array = PlanarArray(num_rows=1,
                             num_cols=1,
                             vertical_spacing=0.5,
                             horizontal_spacing=0.5,
                             pattern="iso",
                             polarization="V")
tx = Transmitter("tx",[-3.5,-3.5,3])
scene.add(tx)

rx = Receiver("rx",[3.5,3.5,1.2],[0.0,0.0,0.0])
scene.add(rx)
cm = scene.coverage_map()
scene.preview(coverage_map=cm)
scene.frequency = 2.4e9
paths = scene.compute_paths(max_depth=5,
                            num_samples=1e6)
# Show the coordinates of the starting points of all rays.
# These coincide with the location of the transmitters.
print("Source coordinates: ", paths.sources.numpy())
print("Transmitter coordinates: ", list(scene.transmitters.values())[0].position.numpy())

# Show the coordinates of the endpoints of all rays.
# These coincide with the location of the receivers.
print("Target coordinates: ",paths.targets.numpy())
print("Receiver coordinates: ",list(scene.receivers.values())[0].position.numpy())

# Show the types of all paths:
# 0 - LoS, 1 - Reflected, 2 - Diffracted, 3 - Scattered
# Note that Diffraction and scattering are turned off by default.
print("Path types: ", paths.types.numpy())

# We can now access for every path the channel coefficient, the propagation delay,
# as well as the angles of departure and arrival, respectively (zenith and azimuth). 

# Let us inspect a specific path in detail 
path_idx = 1 # Try out other values in the range [0, 13]

# For a detailed overview of the dimensions of all properties, have a look at the API documentation
print(f"\n--- Detailed results for path {path_idx} ---")
print(f"Channel coefficient: {paths.a[0,0,0,0,0,path_idx, 0].numpy()}")
print(f"Propagation delay: {paths.tau[0,0,0,path_idx].numpy()*1e6:.5f} us")
print(f"Zenith angle of departure: {paths.theta_t[0,0,0,path_idx]:.4f} rad")
print(f"Azimuth angle of departure: {paths.phi_t[0,0,0,path_idx]:.4f} rad")
print(f"Zenith angle of arrival: {paths.theta_r[0,0,0,path_idx]:.4f} rad")
print(f"Azimuth angle of arrival: {paths.phi_r[0,0,0,path_idx]:.4f} rad")
```

**Comment by zhiha** [comment] 2023-10-11 10:47
Here is my scene:
[room_init.zip](https://github.com/NVlabs/sionna/files/12868471/room_init.zip)

**Comment by jhoydis** [comment] 2023-10-11 13:21
Hi, after a quick check, there are a couple of things that go wrong.

1) The paths with zero energy and zero delay are duplicates which should have a delay of -1, which did not get correctly updated. However, this has no impact on the actual channel impulse response. You can check ``paths.mask`` and verify that these paths are ``False``. This is a small bug which will get fixed in the next release.

2) For some reason, some normals in your scene are incorrectly computed and get NaN. This leads to NaNs in the CIR which is not good. We'll look into it.

**Comment by jhoydis** [comment] 2023-10-12 09:16
I had a look at your scene in Blender. It turns out that the scene is not well designed. You have many overlapping vertices in the walls which Sionna RT/Mitsuba cannot handle. It seems that the walls are not planes but have been obtained by collapsing cubes (or something like this).

There are many tutorials available that show how you can remove overlapping vertices, e.g., https://www.youtube.com/watch?v=vmyqUagUq4k&t=2s


My advice would be to recreate the scene by making sure that the walls are planes. You could even join the walls and make sure that they share the same vertices.

**Comment by zhiha** [comment] 2023-10-12 09:27
I got it! Thanks a lot!

**Closed** 2023-10-13 00:45 UTC
