### ISSUE TITLE
Error with GPU running 5G NR PUSCH end-to-end model

### ISSUE THREAD

**Issue by just1nGH** [NVlabs/sionna#307] opened 2024-01-05 11:26 UTC
Hi,
I have some running issue with the example in 0.16.1 documentation (https://nvlabs.github.io/sionna/examples/5G_NR_PUSCH.html#End-to-end-PUSCH-Simulations)
Running OK with CPUs(gpu_num = ""), but Error with GPU(gpu_num = 0). 
Have you got any idea on how to fix the issue?

Here is some information:
Ubuntu 20.04.6 LTS
Python 3.8.10
TensorFlow 2.13.1
Sionna 0.16.1
NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7
LD_LIBRARY_PATH :/usr/local/cuda-11.7/lib64

cell output:
```
---------------------------------------------------------------------------
**FailedPreconditionError**                   Traceback (most recent call last)
Cell In[13], line 23
     21 for detector in PUSCH_SIMS["detector"]:
     22     model = Model(scenario, perfect_csi, domain, detector, PUSCH_SIMS["speed"])
---> 23     ber, bler = sim_ber(model,
     24                 PUSCH_SIMS["ebno_db"],
     25                 batch_size=batch_size,
     26                 max_mc_iter=1000,
     27                 num_target_block_errors=200)
     28     PUSCH_SIMS["ber"].append(list(ber.numpy()))
     29     PUSCH_SIMS["bler"].append(list(bler.numpy()))

File /usr/local/lib/python3.8/dist-packages/sionna/utils/misc.py:750, in sim_ber(mc_fun, ebno_dbs, batch_size, max_mc_iter, soft_estimates, num_target_bit_errors, num_target_block_errors, target_ber, target_bler, early_stop, graph_mode, distribute, verbose, forward_keyboard_interrupt, callback, dtype)
    745     b, b_hat = _run_distributed(strategy,
    746                                 mc_fun,
    747                                 batch_size,
    748                                 ebno_dbs[i])
    749 else:
--> 750     outputs = mc_fun(batch_size=batch_size, ebno_db=ebno_dbs[i])
    751     # assume first and second return value is b and b_hat
    752     # other returns are ignored
    753     b = outputs[0]

File /usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py:53, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51 try:
     52   ctx.ensure_initialized()
---> 53   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                       inputs, attrs, num_outputs)
     55 except core._NotOkStatusException as e:
     56   if name is not None:

FailedPreconditionError: Exception encountered when calling layer 'model' (type Model).

**DNN library initialization failed**. Look at the errors above for more details. [Op:__inference_call_28591]

Call arguments received by layer 'model' (type Model):
  • batch_size=tf.Tensor(shape=(), dtype=int32)
  • ebno_db=tf.Tensor(shape=(), dtype=float32)
```

**Comment by merlinND** [comment] 2024-01-08 08:58
Hello @just1nGH,

Thank you for reporting this issue. It looks similar to #255, however it was supposed to be fixed in Sionna v0.16 and / or with TensorFlow 2.13.

Did you encounter this error with XLA disabled as well?

**Comment by just1nGH** [comment] 2024-01-08 09:41
Hello @merlinND ,

Thank you for your quick response.

Yes we have Sionna 0.16 & Tesnsorflow 2.13. So it might be a different problem as they actually reports different errors:
#377 FailedPreconditionError(sionna.config.xla_compat = True) vs #255 InvalidArgumentError.

Following your suggestion, putting sionna.config.xla_compat = False, I have an error exactly like #255.

To summarise:
- with sionna.config.xla_compat = True, I have FailedPreconditionError.
- with sionna.config.xla_compat = True, I have InvalidArgumentError.

Thanks for your time.

**Comment by SebastianCa** [comment] 2024-01-08 18:11
Hi,
it seems like there is an issue with your local TF installation / GPU driver. 
Have you tried to run any other tutorial notebook in graph mode?

**Comment by just1nGH** [comment] 2024-01-09 12:46
Here are the findings from two tests I did this morning:

1) https://nvlabs.github.io/sionna/examples/Discover_Sionna.html#Run-some-Throughput-Tests-(Graph-Mode)
The three modes are all running successfully.  However, the Graph + XLA is at the same running speed as Eager mode, much slower than the Graph mode. The results as below
•	Throughput in eager execution: 1.18 Mb/s
•	Throughput in graph execution: 6.81 Mb/s
•	Throughput in graph execution with XLA: 1.18 Mb/s

2) https://nvlabs.github.io/sionna/examples/5G_NR_PUSCH.html#End-to-end-PUSCH-Simulations
This is the PUSCH example we previously run, default running on GRAPH + XLA (that was the reason we had problem originally), with both k-best and l-mmse decoders. Here are the results.
•	With l-mmse decoder, both Eager mode and Graph mode worked. The Graph mode had a running speed comparable to the Sionna reference, while the Eager mode was around 4 times slower.
•	With k-best decoder, Eager mode and Graph mode failed with FailedPreconditionError, probably because a bug 
•	The Graph + XLA mode did not work for both decoders due to an InvalidArgumentError (No registered ‘MatrixSquareRoot’ OpKernel for XLA_GPU_JIT devices).

To summary:
-  The k-best decoder did not work on any mode, may be a bug?
- For the problem with the Graph+XLA Mode
  - on Example 1, it was running successfully, it is expected running faster than the Graph mode,  but shows a  much slower speed
  - on Example 2, failed due to  the absence of a registered 'MatrixSquareRoot' OpKernel for XLA_GPU_JIT devices.

Any ideas?

Thanks

**Comment by SebastianCa** [comment] 2024-01-11 10:47
Hi,
I cannot reproduce the issue on my local setup. However, we noticed that your NVIDIA drivers / CUDA version is a bit behind. We observed a performance degradation in a similar context and it might help to upgrade your system.

Regarding the 'MatrixSquareRoot' issue. Please ensure that you set `sionna.config.xla_compat=True`  before running XLA mode.

**Comment by jhoydis** [comment] 2024-04-23 14:32
Closed due to inactivity.

**Closed by jhoydis** 2024-04-23 14:32 UTC
