### ISSUE TITLE
Error in the code examples in "MIMO OFDM Transmissions over the CDL Channel Model"

### ISSUE THREAD

**Issue by choonoKw** [NVlabs/sionna#489] opened 2024-06-17 16:34 UTC
Dear Whom It May Concern,

I was following the codes posted in [MIMO OFDM Transmissions over the CDL Channel Model](https://nvlabs.github.io/sionna/examples/MIMO_OFDM_Transmissions_over_CDL.html). 

When I following from [1] to [4], the code block in [4] does not work with the following message:

rg = ResourceGrid(num_ofdm_symbols=14,
                  fft_size=76,
                  subcarrier_spacing=15e3,
                  num_tx=1,
                  num_streams_per_tx=num_streams_per_tx,
                  cyclic_prefix_length=6,
                  num_guard_carriers=[5,6],
                  dc_null=True,
                  pilot_pattern="kronecker",
                  pilot_ofdm_symbol_indices=[2,11])

*** ValueError: Cannot interpret `dtype` argument. Expected a string or an instance of DTypePolicy. Received: dtype=<dtype: 'complex64'>

**Comment by SebastianCa** [comment] 2024-06-17 16:43
Hi @choonoKw,
I cannot reproduce the error in Google Colab. Is it possible that your local setup uses TensorFlow >2.15? If yes, this version is currently not supported (see #361).

**Comment by SebastianCa** [comment] 2024-06-19 11:46
Closing this issue as it seems to be related to an unsupported TensorFlow version (see #361). 
Feel free to re-open if this is not the case.

**Closed by SebastianCa** 2024-06-19 11:46 UTC
