### ISSUE TITLE
module 'sionna' has no attribute 'config'

### ISSUE THREAD

**Issue by MohanadObeed** [NVlabs/sionna#539] opened 2024-08-08 15:23 UTC
Hi all, I am trying to run the code provided in:  https://nvlabs.github.io/sionna/examples/Discover_Sionna.html#First-Link-level-Simulation

and I get this error "module 'sionna' has no attribute 'config' "

This error occurred at the line "x_hat, no_eff = self._equalizer(y_dt, h_dt_desired, s) "

Does anyone have any clue how to resolve this issue?

Note that config attribute is there but this error persists.

**Comment by merlinND** [comment] 2024-08-09 07:58
Closing as duplicate of #468, please post your symptoms and what you tried to resolve the issue in that thread.

**Closed by merlinND** 2024-08-09 07:58 UTC
