### ISSUE TITLE
Issue in Controlling Position and Orientation of Scene Objects

### ISSUE THREAD

**Issue by Jedrek09** [NVlabs/sionna#578] opened 2024-09-16 09:31 UTC
While executing the code 

```py
scene = load_scene(sionna.rt.scene.simple_street_canyon_with_cars)
scene.add(Camera("cam", position=[50,0,130], look_at=[10,0,0]))
if colab_compat:
    scene.render(camera="cam", num_samples=512);
    raise ExitCell
scene.preview()
```

I got the following error:

```
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 scene = load_scene(sionna.rt.scene.simple_street_canyon_with_cars)
      2 scene.add(Camera("cam", position=[50,0,130], look_at=[10,0,0]))
      3 if colab_compat:

AttributeError: module 'sionna.rt.scene' has no attribute 'simple_street_canyon_with_cars'
```

How to solve this??

**Comment by merlinND** [comment] 2024-09-16 10:27
Closing as duplicate of #577 as it's likely due to the same problem.

**Closed by merlinND** 2024-09-16 10:27 UTC
